stages:
  - test
  - deploy

image: zoltannz/python-with-gcloud

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_VENV_IN_PROJECT: "true"
  LANG: "en_NZ.UTF-8"
  LC_ALL: "en_NZ.UTF-8"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - pip install pipenv
  - pipenv run setup

test:
  stage: test
  script:
    - pipenv run lint
    - pipenv run test
    - pipenv run cov-report

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=my-hello-world-app-staging --api-key=$HEROKU_STAGING_API_KEY
  environment:
    name: staging
    url: https://my-hello-world-app-staging.herokuapp.com
  only:
    - master

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=my-hello-world-app-production --api-key=$HEROKU_PRODUCTION_API_KEY
  when: manual
  environment:
    name: production
    url: https://my-hello-world-app-production.herokuapp.com
  only:
    - master
