stages:
  - test
  - deploy

image: zoltannz/python-with-gcloud

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PIPENV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pipenv"
  PIPENV_VENV_IN_PROJECT: "true"
  LANG: "en_NZ.UTF-8"
  LC_ALL: "en_NZ.UTF-8"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V
  - pip install pipenv
  - pipenv run setup

test:
  stage: test
  script:
    - pipenv run lint
    - pipenv run test
    - pipenv run cov-report

staging:
  stage: deploy
  script:
    - echo "TODO Add deployment steps to staging environment."
  environment:
    name: staging
    url: https://gitlab.com/zoltan-nz/ci-cd-pipeline-template-for-data-projects
  only:
    - master

production:
  stage: deploy
  script:
    - echo "TODO Add deployment steps to production environment."
  when: manual
  environment:
    name: production
    url: https://gitlab.com/zoltan-nz/ci-cd-pipeline-template-for-data-projects
  only:
    - master
